- type: job
  id: CaesarLegionCenturion
  setPreference: true
  name: job-name-caesar-legion-centurion
  description: job-description-caesar-legion-centurion
  playTimeTracker: CaesarLegionCenturion
  requirements:
  - !type:CharacterDepartmentTimeRequirement
      department: CaesarLegion
      min: 216000 # 60 hours
  - !type:CharacterPlaytimeRequirement
      tracker: CaesarLegionDecan
      min: 43200 # 12 hours
  - !type:CharacterSpeciesRequirement
    species:
    - Human
  - !type:CharacterSexRequirement
    sex: Male
  - !type:CharacterGenderRequirement
    gender: Male
  startingGear: CaesarLegionCenturionGear
  alwaysUseSpawner: true
  icon: "JobIconLegioner"
  supervisors: job-name-caesar-legion-high
  canBeAntag: false
  access:
  - CaesarLegionCenturion
  - CaesarLegion
  - CaesarLegionDecan

- type: startingGear
  id: CaesarLegionCenturionGear
  equipment:
    jumpsuit: N14ClothingUniformJumpskirtCaesarLegion
    neck: ClothingNeckBrownScarf
    eyes: N14ClothingEyesGlassesWelding
    back: N14ClothingBackpackMilitary
    shoes: N14ClothingBootsCaesarLegionCenturion
    gloves: N14ClothingHandsGlovesCaesarLegionCenturion
    belt: ClothingBeltRope
    pocket1: N14WeaponPistol10mmPipe
    pocket2: N14WeaponPistol10mmPipe
    id: N14IDCaesarLegionCenturionMedal
  storage:
    back:
    - N14BoxPlasticFilledMilitary

- type: playTimeTracker
  id: CaesarLegionCenturion
