- type: job
  id: CaesarLegionDecan
  setPreference: true
  name: job-name-caesar-legion-decan
  description: job-description-caesar-legion-decan
  playTimeTracker: CaesarLegionDecan
  requirements:
  - !type:CharacterDepartmentTimeRequirement
    department: CaesarLegion
    min: 72000 # 20 hours
  - !type:CharacterPlaytimeRequirement
      tracker: CaesarLegionVeteran
      min: 18000 # 5 hours
  - !type:CharacterSpeciesRequirement
    species:
    - Human
  - !type:CharacterSexRequirement
    sex: Male
  - !type:CharacterGenderRequirement
    gender: Male
  startingGear: CaesarLegionDecanGear
  alwaysUseSpawner: true
  icon: "JobIconLegioner"
  supervisors: job-name-caesar-legion-mid
  canBeAntag: false
  access:
  - CaesarLegion
  - CaesarLegionDecan

- type: startingGear
  id: CaesarLegionDecanGear
  equipment:
    jumpsuit: N14ClothingUniformJumpskirtCaesarLegion
    neck: ClothingNeckRedScarf
    eyes: N14ClothingEyesGlassesWelding
    back: N14ClothingBackpackMilitary
    shoes: N14ClothingBootsBlack
    gloves: N14ClothingHandsGlovesTribal
    belt: ClothingBeltRope
    pocket1: N14WeaponPistol10mmPipe
    pocket2: N14WeaponPistol10mmPipe
    id: N14IDCaesarLegionDecanMedal
  storage:
    back:
    - N14BoxPlasticFilledMilitary

- type: playTimeTracker
  id: CaesarLegionDecan
